from tags import get_pybites_top_tags


def test_get_pybites_top_10_tags():
    expected = [('python', 79),
                ('learning', 79),
                ('codechallenges', 72),
                ('twitter', 62),
                ('tips', 61),
                ('flask', 52),
                ('news', 49),
                ('django', 37),
                ('code', 25),
                ('github', 24)]
    actual = get_pybites_top_tags()
    assert actual == expected


def test_get_pybites_top_5_tags():
    expected = [('python', 79),
                ('learning', 79),
                ('codechallenges', 72),
                ('twitter', 62),
                ('tips', 61)]
    actual = get_pybites_top_tags(n=5)
    assert actual == expected

    [('python', 79), ('learning', 79), ('codechallenges', 72), ('twitter', 62), ('tips', 61), ('flask', 52),
     ('news', 49), ('django', 37), ('code', 25), ('github', 24), ('automation', 23), ('data science', 21), ('apis', 21),
     ('books', 20), ('pybites', 20), ('api', 19), ('tricks', 18), ('jupyter', 17), ('machine learning', 17),
     ('code review', 15), ('regex', 14), ('pandas', 14), ('beginners', 14), ('refactoring', 13),
     ('100daysofdjango', 13), ('podcasts', 12), ('twilio', 11), ('data', 11), ('tools', 11), ('oop', 11),
     ('heroku', 11), ('testing', 11), ('decorators', 11), ('cleancode', 11), ('data analysis', 10), ('vim', 10),
     ('pytest', 10), ('tutorial', 10), ('aws', 10), ('resources', 10), ('pythonic', 10), ('docker', 9), ('slack', 9),
     ('guest', 9), ('packaging', 9), ('git', 9), ('requests', 9), ('bestpractices', 9), ('tutorials', 8), ('pillow', 8),
     ('beginner', 8), ('matplotlib', 8), ('pypi', 8), ('game', 8), ('generators', 8), ('raspberry pi', 7), ('json', 7),
     ('data visualisation', 7), ('bokeh', 7), ('challenges', 7), ('logging', 7), ('rest', 7), ('programming', 7),
     ('cli', 7), ('webscraping', 7), ('tensorflow', 6), ('community', 6), ('csv', 6), ('collections', 6), ('bottle', 6),
     ('bettercodehub', 6), ('email', 6), ('selenium', 6), ('virtualenv', 6), ('algorithms', 6), ('movies', 6),
     ('classes', 6), ('pelican', 6), ('namedtuples', 6), ('stdlib', 6), ('opencv', 5), ('numpy', 5), ('asyncio', 5),
     ('deep learning', 5), ('counter', 5), ('facebook', 5), ('ai', 5), ('hacktoberfest', 5), ('tweepy', 5),
     ('code quality', 5), ('unittest', 5), ('lambda', 5), ('pycharm', 5), ('itertools', 5), ('platform', 5),
     ('review', 5), ('images', 5), ('tkinter', 5), ('beautifulsoup', 5), ('pip', 5), ('sqlite3', 5), ('feedparser', 5),
     ('blog', 5), ('data structures', 5), ('3.6', 5), ('twitterapi', 5), ('challenge', 4), ('sql', 4), ('sqlite', 4),
     ('modules', 4), ('microservices', 4), ('gui', 4), ('pygame', 4), ('pipenv', 4), ('podcast', 4), ('special', 4),
     ('100daysofcode', 4), ('sig', 4), ('training', 4), ('newquote', 4), ('utilities', 4), ('postgres', 4), ('bot', 4),
     ('polymorphism', 4), ('dunder', 4), ('2vs3', 4), ('dicts', 4), ('xml', 4), ('cron', 4), ('cheat sheet', 4),
     ('contextmanagers', 4), ('iterators', 4), ('scrabble', 4), ('chatbot', 3), ('nlp', 3), ('web development', 3),
     ('cheatsheet', 3), ('parsing', 3), ('daily python tip', 3), ('fixtures', 3), ('dictionaries', 3), ('debugging', 3),
     ('videos', 3), ('design patterns', 3), ('sqlalchemy', 3), ('security', 3), ('kubernetes', 3), ('notifications', 3),
     ('web scraping', 3), ('games', 3), ('unix', 3), ('clean code', 3), ('software development', 3), ('examples', 3),
     ('weather', 3), ('click', 3), ('pybites banner generator', 3), ('flask-sqlalchemy', 3), ('coding', 3), ('pep8', 3),
     ('deployment', 3), ('visualization', 3), ('reddit', 3), ('post', 3), ('textblob', 3), ('peewee', 3),
     ('themoviedb', 3), ('pydata', 3), ('karma', 3), ('pytz', 3), ('100days', 3), ('html', 3), ('encapsulation', 3),
     ('inheritance', 3), ('warcraft', 3), ('pycon', 3), ('inventory', 3), ('performance', 3), ('prediction', 3),
     ('magicmethods', 3), ('similarity', 3), ('datamodel', 3), ('javascript', 2), ('keras', 2), ('scipy', 2),
     ('python alicante', 2), ('marvel', 2), ('bots', 2), ('monitoring', 2), ('regular expressions', 2), ('findall', 2),
     ('twitter api', 2), ('pytip', 2), ('digitalocean', 2), ('cookiecutter', 2), ('packages', 2), ('react', 2),
     ('spotify', 2), ('music', 2), ('sms', 2), ('birthdays', 2), ('lambda function', 2), ('tox', 2), ('zen', 2),
     ('excel', 2), ('openpyxl', 2), ('hacking', 2), ('django rest framework', 2), ('drf', 2), ('mime', 2),
     ('ubuntu', 2), ('ide', 2), ('courses', 2), ('projects', 2), ('bootstrap', 2), ('open source', 2), ('apps', 2),
     ('ipython', 2), ('anaconda', 2), ('conda', 2), ('pyconau', 2), ('curl', 2), ('chrome', 2), ('video', 2),
     ('gmail', 2), ('registration', 2), ('realpython', 2), ('cloud', 2), ('nasa', 2), ('sessions', 2), ('praw', 2),
     ('dailyprogrammer', 2), ('learnpython', 2), ('pathlib', 2), ('audio', 2), ('nltk', 2), ('pytrack', 2),
     ('scikit', 2), ('math', 2), ('scrapy', 2), ('milestone', 2), ('lessons', 2), ('scripts', 2), ('maya', 2),
     ('frameworks', 2), ('series', 2), ('digest', 2), ('type checking', 2), ('imdb', 2), ('dunders', 2),
     ('special methods', 2), ('magic methods', 2), ('operator overloading', 2), ('datetime', 2), ('tracking', 2),
     ('meta', 2), ('strings', 2), ('packt', 2), ('pybonacci', 2), ('ebooks', 2), ('sponsoring', 2), ('elizabeth', 2),
     ('help', 2), ('jinja2', 2), ('calculation', 2), ('electricity', 2), ('property', 2), ('object oriented', 2),
     ('pycon2017', 2), ('copy', 2), ('goodreads', 2), ('google', 2), ('alexa', 2), ('wikipedia', 2), ('quotes', 2),
     ('forismatic', 2), ('mail', 2), ('css', 2), ('dry', 2), ('ebook', 2), ('shell', 2), ('tictactoe', 2), ('yield', 2),
     ('hangman', 2), ('iteration', 2), ('productivity', 2), ('with', 2), ('pyfun', 2), ('guido', 2), ('builtin', 2),
     ('gensim', 2), ('tweets', 2), ('abc', 2), ('tags', 2), ('assert', 2), ('rss', 2), ('venv', 2), ('publishing', 2),
     ('cython', 1), ('nglview', 1), ('book', 1), ('node', 1), ('cryptocurrency', 1), ('http', 1), ('data mapping', 1),
     ('scitkit', 1), ('code challenges', 1), ('live coding', 1), ('retrospective', 1), ('talks', 1), ('fun', 1),
     ('namedtuple', 1), ('live challenge', 1), ('coffee', 1), ('contest', 1), ('ml', 1), ('design', 1), ('pypy', 1),
     ('reportlab', 1), ('pdf', 1), ('tests', 1), ('animation', 1), ('blender', 1), ('sublime', 1), ('deepo', 1),
     ('setup', 1), ('pdb', 1), ('troubleshooting', 1), ('bugs', 1), ('aws lambda', 1), ('pygotham', 1),
     ('computer science', 1), ('caching', 1), ('memoization', 1), ('properties', 1), ('classmethod', 1),
     ('staticmethod', 1), ('lru_cache', 1), ('mock.patch', 1), ('contextmanager', 1), ('ramp', 1),
     ('k-means clustering', 1), ('pyqt', 1), ('qutebrowser', 1), ('pyinstaller', 1), ('survey', 1), ('disqus', 1),
     ('blockchain', 1), ('google facets', 1), ('mypy', 1), ('pytest-cov', 1), ('ci', 1), ('opensource', 1),
     ('talkpython', 1), ('os', 1), ('ntlk', 1), ('jenkins', 1), ('q&amp;a', 1), ('cheat sheets', 1), ('fstrings', 1),
     ('asynchronous python', 1), ('sublime text', 1), ('networkx', 1), ('story', 1), ('learn-by-doing', 1),
     ('inspiration', 1), ('blogging', 1), ('career', 1), ('development', 1), ('pythonistas', 1), ('freecodecamp', 1),
     ('howto', 1), ('software', 1), ('first script', 1), ('vba', 1), ('pinclone', 1), ('codetips', 1), ('bcc', 1),
     ('celery', 1), ('rabbitmq', 1), ('snap', 1), ('swarm', 1), ('nomad', 1), ('pyfiddle', 1), ('concurrency', 1),
     ('wtfpython', 1), ('deepwork', 1), ('pbreadinglist', 1), ('autocomplete', 1), ('sunpy', 1), ('spacing', 1),
     ('tracker', 1), ('selenium-requests', 1), ('scraping', 1), ('nnabla', 1), ('pytorch', 1), ('pybeeware', 1),
     ('markdown', 1), ('mistletoe', 1), ('flask-wtf', 1), ('face recognition', 1), ('thumbler', 1), ('thumbnails', 1),
     ('women', 1), ('history', 1), ('beeware', 1), ('bash', 1), ('scripting', 1), ('authentication', 1),
     ('my first script', 1), ('nodejs', 1), ('sendgrid', 1), ('astronomy', 1), ('comprehension', 1), ('nginx', 1),
     ('game of thrones', 1), ('django-registration', 1), ('guide', 1), ('purecss', 1), ('crispy forms', 1),
     ('qutip', 1), ('facial recognition', 1), ('thonny', 1), ('urllib', 1), ('jobs', 1), ('pexpect', 1),
     ('pythonanywhere', 1), ('anyprint', 1), ('quart', 1), ('iot', 1), ('submission', 1), ('planet python', 1),
     ('postgresql', 1), ('pyramid', 1), ('fat', 1), ('interview', 1), ('fedora', 1), ('word clouds', 1), ('easygui', 1),
     ('lisp', 1), ('toolkits', 1), ('argparse', 1), ('mailgun', 1), ('siri', 1), ('voice', 1), ('pgcli', 1),
     ('mycli', 1), ('macos', 1), ('mongodb', 1), ('pymongo', 1), ('constructors', 1), ('ports', 1), ('init', 1),
     ('imports', 1), ('omdb', 1), ('picle', 1), ('socketserver', 1), ('orm', 1), ('variables', 1), ('plotly', 1),
     ('solid', 1), ('pendulum', 1), ('timezones', 1), ('pygithub', 1), ('pr template', 1), ('py', 1), ('instagram', 1),
     ('charts', 1), ('faker', 1), ('readme', 1), ('indentation', 1), ('mock', 1), ('geo', 1), ('pickle', 1),
     ('packtpub', 1), ('objects', 1), ('sentiment analysis', 1), ('vader', 1), ('r', 1), ('data cleaning', 1),
     ('energy', 1), ('python anywhere', 1), ('pythonista 3', 1), ('puzzles', 1), ('arrays', 1), ('finance', 1),
     ('signalconf', 1), ('computation', 1), ('getter', 1), ('setter', 1), ('adventure', 1), ('rooms', 1), ('pep', 1),
     ('boilerplates', 1), ('memory', 1), ('gitsuggest', 1), ('conference', 1), ('networking', 1), ('parallel', 1),
     ('mentoring', 1), ('photos', 1), ('abcs', 1), ('bpython', 1), ('mentors', 1), ('speedml', 1), ('pcap', 1),
     ('unity3d', 1), ('oauth', 1), ('manning', 1), ('netflix', 1), ('recommendation engine', 1), ('parrotread', 1),
     ('recommender system', 1), ('pandoc', 1), ('continuum', 1), ('visual studio', 1), ('birthday', 1), ('calendar', 1),
     ('icalendar', 1), ('recommendations', 1), ('word cloud', 1), ('terminal', 1), ('ascii', 1), ('booleans', 1),
     ('motivation', 1), ('twython', 1), ('twythonstreamer', 1), ('slacker', 1), ('configparser', 1), ('brand', 1),
     ('triggers', 1), ('passwords', 1), ('folium', 1), ('task manager', 1), ('reading planner', 1), ('meal history', 1),
     ('openweathermap', 1), ('deploy', 1), ('jinja', 1), ('softskills', 1), ('todo', 1), ('iterm2', 1), ('pygamels', 1),
     ('arguments', 1), ('cookbook', 1), ('safari books', 1), ('ruby', 1), ('sort', 1), ('defaultdict', 1), ('loops', 1),
     ('nohup', 1), ('rating', 1), ('mechanize', 1), ('jupiter', 1), ('shortcuts', 1), ('flake8', 1), ('howdoi', 1),
     ('conque', 1), ('nerdtree', 1), ('pyperclip', 1), ('glob', 1), ('ipaddress', 1), ('sysadmin', 1), ('six', 1),
     ('python-modernize', 1), ('porting', 1), ('future', 1), ('2to3', 1), ('coverage', 1), ('futurize', 1),
     ('caniusepython3', 1), ('werkzeug', 1), ('forks', 1), ('cache', 1), ('package', 1), ('fire', 1), ('cpython', 1),
     ('paramiko', 1), ('google docs', 1), ('pygsheets', 1), ('commands', 1), ('list', 1), ('mutable', 1),
     ('deepcopy', 1), ('contextlib', 1), ('tuples', 1), ('stackoverflow', 1), ('app', 1), ('sentiment', 1), ('map', 1),
     ('patterns', 1), ('functional programming', 1), ('shelve', 1), ('database', 1), ('k-means', 1), ('histogram', 1),
     ('socialmedia', 1), ('googletrends', 1), ('reference', 1), ('hackersguide', 1), ('f-string', 1), ('slicing', 1),
     ('objectoriented', 1), ('grumpy', 1), ('async', 1), ('delegator', 1), ('pyprojects', 1), ('exceptions', 1),
     ('zen of python', 1), ('error handling', 1), ('anti-patterns', 1), ('fork', 1), ('random', 1), ('sets', 1),
     ('hn', 1), ('max', 1), ('notebooks', 1), ('permutations', 1), ('bs4', 1), ('tdd', 1), ('pythontips', 1),
     ('git flow', 1), ('guidelines', 1), ('coding style', 1), ('features', 1), ('release', 1), ('formatting', 1),
     ('typing', 1), ('secrets', 1), ('readability', 1), ('pyvenv', 1), ('gotchas', 1), ('kindle', 1),
     ('template strings', 1), ('bookcision', 1), ('zip', 1), ('distribute', 1), ('deque', 1)]
